//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Musicalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog
    {
        public long AlbumID { get; set; }
        public string AlbumName { get; set; }
        public string Artist { get; set; }
        public string Type { get; set; }
        public Nullable<long> Stock { get; set; }
    }
}
